---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: custom-policy-demo
    category: Custom
spec:
  extends:
    - name: extension-definition
      namespace: default
  properties:
    stringProperty:
      type: string
      default: some value
  required:
    - stringProperty
